// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obicon.Server.Data;

#nullable disable

namespace Obicon.Server.Data.Migrations
{
    [DbContext(typeof(ObiconDbContext))]
    [Migration("20261003222028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obicon.Server.Models.EnrollToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PoolId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EnrollTokens");
                });

            modelBuilder.Entity("Obicon.Server.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnrollmentType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalIpv4")
                        .HasColumnType("text");

                    b.Property<string>("ExternalIpv6")
                        .HasColumnType("text");

                    b.Property<string>("InternalIpv4")
                        .HasColumnType("text");

                    b.Property<string>("InternalIpv6")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthToken");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Obicon.Server.Models.NodePool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("NodePools");
                });

            modelBuilder.Entity("Obicon.Server.Models.ServerSettingValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("ServerSettingValues");
                });

            modelBuilder.Entity("Obicon.Server.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CacheBust")
                        .HasColumnType("boolean");

                    b.Property<int?>("CheckCertificateExpiryDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnsNameserver")
                        .HasColumnType("text");

                    b.Property<string>("DnsQueryType")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedBodyPattern")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedDnsResult")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedStatusCodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("FollowRedirects")
                        .HasColumnType("boolean");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text");

                    b.Property<int>("IpVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NodeIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("PingCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PingIntervalMs")
                        .HasColumnType("integer");

                    b.Property<int?>("PingTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<string>("PoolIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TracerouteMaxHops")
                        .HasColumnType("integer");

                    b.Property<int?>("TracerouteQueriesPerHop")
                        .HasColumnType("integer");

                    b.Property<int?>("TracerouteQueryTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<bool?>("TracerouteResolveHostnames")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CacheBust")
                        .HasColumnType("boolean");

                    b.Property<int?>("CheckCertificateExpiryDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnsNameserver")
                        .HasColumnType("text");

                    b.Property<string>("DnsQueryType")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedBodyPattern")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedDnsResult")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedStatusCodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("FollowRedirects")
                        .HasColumnType("boolean");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text");

                    b.Property<int>("IpVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PingCount")
                        .HasColumnType("integer");

                    b.Property<int?>("PingIntervalMs")
                        .HasColumnType("integer");

                    b.Property<int?>("PingTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.Property<int>("TestType")
                        .HasColumnType("integer");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TracerouteMaxHops")
                        .HasColumnType("integer");

                    b.Property<int?>("TracerouteQueriesPerHop")
                        .HasColumnType("integer");

                    b.Property<int?>("TracerouteQueryTimeoutMs")
                        .HasColumnType("integer");

                    b.Property<bool?>("TracerouteResolveHostnames")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "Status");

                    b.HasIndex("Status", "CompletedAt");

                    b.ToTable("TestJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
