// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Obicon.Server.Data;

#nullable disable

namespace Obicon.Server.Data.Migrations
{
    [DbContext(typeof(ObiconDbContext))]
    [Migration("20261004120659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Obicon.Server.Models.EnrollToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.ToTable("enroll_tokens");
                });

            modelBuilder.Entity("Obicon.Server.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EnrollmentType")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_type");

                    b.Property<string>("ExternalIpv4")
                        .HasColumnType("text")
                        .HasColumnName("external_ipv4");

                    b.Property<string>("ExternalIpv6")
                        .HasColumnType("text")
                        .HasColumnName("external_ipv6");

                    b.Property<string>("InternalIpv4")
                        .HasColumnType("text")
                        .HasColumnName("internal_ipv4");

                    b.Property<string>("InternalIpv6")
                        .HasColumnType("text")
                        .HasColumnName("internal_ipv6");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AuthToken");

                    b.ToTable("nodes");
                });

            modelBuilder.Entity("Obicon.Server.Models.NodeLabel", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.HasKey("NodeId", "Label");

                    b.ToTable("node_labels");
                });

            modelBuilder.Entity("Obicon.Server.Models.NodePool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("node_pools");
                });

            modelBuilder.Entity("Obicon.Server.Models.NodeReportedSetting", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("NodeId", "Key");

                    b.ToTable("node_reported_settings");
                });

            modelBuilder.Entity("Obicon.Server.Models.PoolMember", b =>
                {
                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.HasKey("PoolId", "NodeId");

                    b.HasIndex("NodeId");

                    b.ToTable("pool_members");
                });

            modelBuilder.Entity("Obicon.Server.Models.ServerSettingValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("server_setting_values");
                });

            modelBuilder.Entity("Obicon.Server.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CacheBust")
                        .HasColumnType("boolean")
                        .HasColumnName("cache_bust");

                    b.Property<int?>("CheckCertificateExpiryDays")
                        .HasColumnType("integer")
                        .HasColumnName("check_certificate_expiry_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DnsNameserver")
                        .HasColumnType("text")
                        .HasColumnName("dns_nameserver");

                    b.Property<string>("DnsQueryType")
                        .HasColumnType("text")
                        .HasColumnName("dns_query_type");

                    b.Property<string>("ExpectedBodyPattern")
                        .HasColumnType("text")
                        .HasColumnName("expected_body_pattern");

                    b.Property<string>("ExpectedDnsResult")
                        .HasColumnType("text")
                        .HasColumnName("expected_dns_result");

                    b.Property<string>("ExpectedStatusCodes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_status_codes");

                    b.Property<bool?>("FollowRedirects")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_redirects");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<int>("IpVersion")
                        .HasColumnType("integer")
                        .HasColumnName("ip_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scheduled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PingCount")
                        .HasColumnType("integer")
                        .HasColumnName("ping_count");

                    b.Property<int?>("PingIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("ping_interval_ms");

                    b.Property<int?>("PingTimeoutMs")
                        .HasColumnType("integer")
                        .HasColumnName("ping_timeout_ms");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text")
                        .HasColumnName("proxy_url");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<int?>("TracerouteMaxHops")
                        .HasColumnType("integer")
                        .HasColumnName("traceroute_max_hops");

                    b.Property<int?>("TracerouteQueriesPerHop")
                        .HasColumnType("integer")
                        .HasColumnName("traceroute_queries_per_hop");

                    b.Property<int?>("TracerouteQueryTimeoutMs")
                        .HasColumnType("integer")
                        .HasColumnName("traceroute_query_timeout_ms");

                    b.Property<bool?>("TracerouteResolveHostnames")
                        .HasColumnType("boolean")
                        .HasColumnName("traceroute_resolve_hostnames");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestHeader", b =>
                {
                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("TestId", "Name");

                    b.ToTable("test_headers");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<bool>("CacheBust")
                        .HasColumnType("boolean")
                        .HasColumnName("cache_bust");

                    b.Property<int?>("CheckCertificateExpiryDays")
                        .HasColumnType("integer")
                        .HasColumnName("check_certificate_expiry_days");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DnsNameserver")
                        .HasColumnType("text")
                        .HasColumnName("dns_nameserver");

                    b.Property<string>("DnsQueryType")
                        .HasColumnType("text")
                        .HasColumnName("dns_query_type");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExpectedBodyPattern")
                        .HasColumnType("text")
                        .HasColumnName("expected_body_pattern");

                    b.Property<string>("ExpectedDnsResult")
                        .HasColumnType("text")
                        .HasColumnName("expected_dns_result");

                    b.Property<string>("ExpectedStatusCodes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_status_codes");

                    b.Property<bool?>("FollowRedirects")
                        .HasColumnType("boolean")
                        .HasColumnName("follow_redirects");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<int>("IpVersion")
                        .HasColumnType("integer")
                        .HasColumnName("ip_version");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<int?>("PingCount")
                        .HasColumnType("integer")
                        .HasColumnName("ping_count");

                    b.Property<int?>("PingIntervalMs")
                        .HasColumnType("integer")
                        .HasColumnName("ping_interval_ms");

                    b.Property<int?>("PingTimeoutMs")
                        .HasColumnType("integer")
                        .HasColumnName("ping_timeout_ms");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text")
                        .HasColumnName("proxy_url");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<int>("TestType")
                        .HasColumnType("integer")
                        .HasColumnName("test_type");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<int?>("TracerouteMaxHops")
                        .HasColumnType("integer")
                        .HasColumnName("traceroute_max_hops");

                    b.Property<int?>("TracerouteQueriesPerHop")
                        .HasColumnType("integer")
                        .HasColumnName("traceroute_queries_per_hop");

                    b.Property<int?>("TracerouteQueryTimeoutMs")
                        .HasColumnType("integer")
                        .HasColumnName("traceroute_query_timeout_ms");

                    b.Property<bool?>("TracerouteResolveHostnames")
                        .HasColumnType("boolean")
                        .HasColumnName("traceroute_resolve_hostnames");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NodeId", "Status");

                    b.HasIndex("Status", "CompletedAt");

                    b.HasIndex("TestId", "CompletedAt");

                    b.ToTable("test_jobs");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobCertificate", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<double?>("DaysRemaining")
                        .HasColumnType("double precision")
                        .HasColumnName("days_remaining");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTime?>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.PrimitiveCollection<List<string>>("SubjectAlternativeNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("subject_alternative_names");

                    b.HasKey("JobId");

                    b.ToTable("test_job_certificates");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobDnsDetails", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("AnsweringNameserver")
                        .HasColumnType("text")
                        .HasColumnName("answering_nameserver");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("ExpectedAddress")
                        .HasColumnType("text")
                        .HasColumnName("expected_address");

                    b.Property<bool?>("ExpectedMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("expected_matched");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<double?>("NameserverRttMs")
                        .HasColumnType("double precision")
                        .HasColumnName("nameserver_rtt_ms");

                    b.PrimitiveCollection<List<string>>("NameserversQueried")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("nameservers_queried");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_type");

                    b.PrimitiveCollection<List<string>>("Resolved")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("resolved");

                    b.Property<string>("ResponseStatus")
                        .HasColumnType("text")
                        .HasColumnName("response_status");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("via");

                    b.HasKey("JobId");

                    b.ToTable("test_job_dns_details");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobDnsRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_type");

                    b.Property<long>("TtlSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("ttl_seconds");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("test_job_dns_records");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobHeader", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("JobId", "Name");

                    b.ToTable("test_job_headers");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobHttpDetails", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<bool?>("BodyMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("body_matched");

                    b.Property<long?>("BytesRead")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_read");

                    b.Property<bool?>("BytesTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("bytes_truncated");

                    b.Property<double?>("ConnectMs")
                        .HasColumnType("double precision")
                        .HasColumnName("connect_ms");

                    b.Property<double?>("DnsMs")
                        .HasColumnType("double precision")
                        .HasColumnName("dns_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FinalUrl")
                        .HasColumnType("text")
                        .HasColumnName("final_url");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("ProxyUrl")
                        .HasColumnType("text")
                        .HasColumnName("proxy_url");

                    b.Property<string>("ReasonPhrase")
                        .HasColumnType("text")
                        .HasColumnName("reason_phrase");

                    b.Property<string>("ResolvedAddress")
                        .HasColumnType("text")
                        .HasColumnName("resolved_address");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TlsCipher")
                        .HasColumnType("text")
                        .HasColumnName("tls_cipher");

                    b.Property<double?>("TlsMs")
                        .HasColumnType("double precision")
                        .HasColumnName("tls_ms");

                    b.Property<string>("TlsProtocol")
                        .HasColumnType("text")
                        .HasColumnName("tls_protocol");

                    b.Property<double?>("TransferMs")
                        .HasColumnType("double precision")
                        .HasColumnName("transfer_ms");

                    b.Property<double?>("TtfbMs")
                        .HasColumnType("double precision")
                        .HasColumnName("ttfb_ms");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("JobId");

                    b.ToTable("test_job_http_details");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobPingDetails", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<double?>("AvgRoundtripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_roundtrip_ms");

                    b.Property<double?>("DnsMs")
                        .HasColumnType("double precision")
                        .HasColumnName("dns_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<double>("LossPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("loss_percent");

                    b.Property<double?>("MaxRoundtripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("max_roundtrip_ms");

                    b.Property<double?>("MinRoundtripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("min_roundtrip_ms");

                    b.Property<int>("Received")
                        .HasColumnType("integer")
                        .HasColumnName("received");

                    b.Property<string>("ReplyAddress")
                        .HasColumnType("text")
                        .HasColumnName("reply_address");

                    b.Property<string>("ReplyStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reply_status");

                    b.Property<string>("ResolvedAddress")
                        .HasColumnType("text")
                        .HasColumnName("resolved_address");

                    b.Property<double?>("RoundtripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("roundtrip_ms");

                    b.Property<int>("Sent")
                        .HasColumnType("integer")
                        .HasColumnName("sent");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<int?>("Ttl")
                        .HasColumnType("integer")
                        .HasColumnName("ttl");

                    b.Property<double?>("WallclockMs")
                        .HasColumnType("double precision")
                        .HasColumnName("wallclock_ms");

                    b.HasKey("JobId");

                    b.ToTable("test_job_ping_details");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobPingReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("ReplyAddress")
                        .HasColumnType("text")
                        .HasColumnName("reply_address");

                    b.Property<string>("ReplyStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reply_status");

                    b.Property<double?>("RoundtripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("roundtrip_ms");

                    b.Property<int?>("Ttl")
                        .HasColumnType("integer")
                        .HasColumnName("ttl");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("test_job_ping_replies");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTcpDetails", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<double?>("ConnectMs")
                        .HasColumnType("double precision")
                        .HasColumnName("connect_ms");

                    b.Property<double?>("DnsMs")
                        .HasColumnType("double precision")
                        .HasColumnName("dns_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Family")
                        .HasColumnType("text")
                        .HasColumnName("family");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("ResolvedAddress")
                        .HasColumnType("text")
                        .HasColumnName("resolved_address");

                    b.HasKey("JobId");

                    b.ToTable("test_job_tcp_details");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTlsDetails", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Cipher")
                        .HasColumnType("text")
                        .HasColumnName("cipher");

                    b.Property<double?>("ConnectMs")
                        .HasColumnType("double precision")
                        .HasColumnName("connect_ms");

                    b.Property<double?>("DnsMs")
                        .HasColumnType("double precision")
                        .HasColumnName("dns_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Family")
                        .HasColumnType("text")
                        .HasColumnName("family");

                    b.Property<double?>("HandshakeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("handshake_ms");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("ResolvedAddress")
                        .HasColumnType("text")
                        .HasColumnName("resolved_address");

                    b.HasKey("JobId");

                    b.ToTable("test_job_tls_details");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteDetails", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("HopCount")
                        .HasColumnType("integer")
                        .HasColumnName("hop_count");

                    b.Property<string>("ResolvedAddress")
                        .HasColumnType("text")
                        .HasColumnName("resolved_address");

                    b.Property<bool>("TargetReached")
                        .HasColumnType("boolean")
                        .HasColumnName("target_reached");

                    b.HasKey("JobId");

                    b.ToTable("test_job_traceroute_details");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteHop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("Hop")
                        .HasColumnType("integer")
                        .HasColumnName("hop");

                    b.Property<string>("Hostname")
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<double?>("RoundtripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("roundtrip_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("test_job_traceroute_hops");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteProbe", b =>
                {
                    b.Property<Guid>("HopId")
                        .HasColumnType("uuid")
                        .HasColumnName("hop_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<double?>("RoundtripMs")
                        .HasColumnType("double precision")
                        .HasColumnName("roundtrip_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("HopId", "Ordinal");

                    b.ToTable("test_job_traceroute_probes");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestTargetNode", b =>
                {
                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.HasKey("TestId", "NodeId");

                    b.HasIndex("NodeId");

                    b.ToTable("test_target_nodes");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestTargetPool", b =>
                {
                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.HasKey("TestId", "PoolId");

                    b.HasIndex("PoolId");

                    b.ToTable("test_target_pools");
                });

            modelBuilder.Entity("Obicon.Server.Models.NodeLabel", b =>
                {
                    b.HasOne("Obicon.Server.Models.Node", null)
                        .WithMany("Labels")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.NodeReportedSetting", b =>
                {
                    b.HasOne("Obicon.Server.Models.Node", null)
                        .WithMany("Settings")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.PoolMember", b =>
                {
                    b.HasOne("Obicon.Server.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obicon.Server.Models.NodePool", null)
                        .WithMany("Members")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestHeader", b =>
                {
                    b.HasOne("Obicon.Server.Models.Test", null)
                        .WithMany("Headers")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobCertificate", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithOne("Certificate")
                        .HasForeignKey("Obicon.Server.Models.TestJobCertificate", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobDnsDetails", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithOne("Dns")
                        .HasForeignKey("Obicon.Server.Models.TestJobDnsDetails", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobDnsRecord", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJobDnsDetails", null)
                        .WithMany("Records")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobHeader", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithMany("Headers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobHttpDetails", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithOne("Http")
                        .HasForeignKey("Obicon.Server.Models.TestJobHttpDetails", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobPingDetails", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithOne("Ping")
                        .HasForeignKey("Obicon.Server.Models.TestJobPingDetails", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobPingReply", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJobPingDetails", null)
                        .WithMany("Replies")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTcpDetails", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithOne("Tcp")
                        .HasForeignKey("Obicon.Server.Models.TestJobTcpDetails", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTlsDetails", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithOne("Tls")
                        .HasForeignKey("Obicon.Server.Models.TestJobTlsDetails", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteDetails", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJob", null)
                        .WithOne("Traceroute")
                        .HasForeignKey("Obicon.Server.Models.TestJobTracerouteDetails", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteHop", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJobTracerouteDetails", null)
                        .WithMany("Hops")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteProbe", b =>
                {
                    b.HasOne("Obicon.Server.Models.TestJobTracerouteHop", null)
                        .WithMany("Probes")
                        .HasForeignKey("HopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestTargetNode", b =>
                {
                    b.HasOne("Obicon.Server.Models.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obicon.Server.Models.Test", null)
                        .WithMany("NodeTargets")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.TestTargetPool", b =>
                {
                    b.HasOne("Obicon.Server.Models.NodePool", null)
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obicon.Server.Models.Test", null)
                        .WithMany("PoolTargets")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Obicon.Server.Models.Node", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Obicon.Server.Models.NodePool", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Obicon.Server.Models.Test", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("NodeTargets");

                    b.Navigation("PoolTargets");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJob", b =>
                {
                    b.Navigation("Certificate");

                    b.Navigation("Dns");

                    b.Navigation("Headers");

                    b.Navigation("Http");

                    b.Navigation("Ping");

                    b.Navigation("Tcp");

                    b.Navigation("Tls");

                    b.Navigation("Traceroute");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobDnsDetails", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobPingDetails", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteDetails", b =>
                {
                    b.Navigation("Hops");
                });

            modelBuilder.Entity("Obicon.Server.Models.TestJobTracerouteHop", b =>
                {
                    b.Navigation("Probes");
                });
#pragma warning restore 612, 618
        }
    }
}
